import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { customerSapRows, visibleSapLine } from "@/lib/sapFormat";
import { trpc } from "@/lib/trpc";
import type { ParsedCustomerOrder } from "@shared/orderTypes";
import { Check, Clipboard, Clock3, History as HistoryIcon, Loader2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function HistoryPage() {
  const history = trpc.orders.history.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const sessions = history.data ?? [];
  const selected = sessions.find(session => session.id === selectedId) ?? sessions[0];

  return <div className="mx-auto max-w-[1480px] text-[#1d2b22]">
    <header className="mb-8 border-b border-[#e5e4dc] pb-7"><div className="mb-3 flex items-center gap-2"><Clock3 className="h-3.5 w-3.5 text-[#78a461]" /><span className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#607266]">Saved parse sessions</span></div><h1 className="text-3xl font-semibold tracking-[-0.035em] sm:text-[38px]">Order history</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#687067]">Reopen previous parsing results and copy the SAP rows for one customer at a time.</p></header>
    {history.isLoading ? <div className="flex min-h-[300px] items-center justify-center text-sm text-[#6b786b]"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading saved orders…</div> : sessions.length === 0 ? <Card className="rounded-[26px] border-[#e4e4dd] bg-white shadow-sm"><CardContent className="flex min-h-[360px] flex-col items-center justify-center p-8 text-center"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#eef5e8] text-[#538151]"><HistoryIcon className="h-6 w-6" /></div><h2 className="mt-5 text-lg font-semibold">No saved orders yet</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#757f76]">After you parse a WhatsApp order, its separate customer SAP blocks will be stored here.</p></CardContent></Card> : <div className="grid gap-7 xl:grid-cols-[360px_minmax(0,1fr)]"><section className="space-y-3">{sessions.map(session => { const customers = session.customers as ParsedCustomerOrder[]; const active = session.id === selected?.id; return <button key={session.id} onClick={() => setSelectedId(session.id)} className={`w-full rounded-2xl border p-4 text-left transition ${active ? "border-[#7ca86b] bg-[#f2f8eb] shadow-sm" : "border-[#e4e4dd] bg-white hover:border-[#bfd1b7]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{customers.length} customer {customers.length === 1 ? "order" : "orders"}</p><p className="mt-1 text-xs text-[#758076]">{new Date(session.createdAt).toLocaleString()}</p></div><Badge className="rounded-lg bg-white px-2 py-1 text-[10px] text-[#56745c] shadow-none hover:bg-white">{customers.reduce((total, customer) => total + customer.sapLines.length, 0)} lines</Badge></div><p className="mt-3 truncate text-xs text-[#607162]">{customers.map(customer => customer.customerName).join(" · ")}</p></button>; })}</section>
      {selected && <section className="rounded-[26px] border border-[#e4e4dd] bg-white p-5 shadow-[0_14px_45px_-32px_rgba(26,49,32,0.25)] sm:p-7"><div className="flex flex-col gap-3 border-b border-[#e5e7df] pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#6c7b6e]">Saved session</p><h2 className="mt-2 text-xl font-semibold tracking-tight">{new Date(selected.createdAt).toLocaleString()}</h2></div><Badge className="w-fit rounded-lg bg-[#e9f4dd] px-2.5 py-1 text-[10px] font-bold tracking-[0.08em] text-[#47703d] hover:bg-[#e9f4dd]">{(selected.customers as ParsedCustomerOrder[]).length} CUSTOMER{(selected.customers as ParsedCustomerOrder[]).length !== 1 ? "S" : ""}</Badge></div><div className="mt-5 space-y-4">{(selected.customers as ParsedCustomerOrder[]).map((customer, index) => <HistoryCustomerBlock customer={customer} index={index} key={`${customer.customerName}-${index}`} />)}</div></section>}
    </div>}
  </div>;
}

function HistoryCustomerBlock({ customer, index }: { customer: ParsedCustomerOrder; index: number }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(customerSapRows(customer)); setCopied(true); toast.success(`SAP rows copied for ${customer.customerName}`); window.setTimeout(() => setCopied(false), 1800); };
  return <Card className="overflow-hidden rounded-2xl border-[#dfe5da] shadow-none"><CardContent className="p-0"><div className="flex flex-col gap-3 border-b border-[#e8ebe4] bg-[#f5f8f2] px-4 py-3.5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#dceccb] text-[11px] font-bold text-[#355d3d]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{customer.customerName}</p><p className="mt-0.5 text-[11px] text-[#788478]">Heading outside SAP rows</p></div></div><Button onClick={copy} variant="outline" size="sm" className="h-9 shrink-0 rounded-lg border-[#cbdac4] bg-white text-xs font-semibold text-[#2e5b3b] hover:bg-[#eef6e8]">{copied ? <Check className="mr-1.5 h-3.5 w-3.5" /> : <Clipboard className="mr-1.5 h-3.5 w-3.5" />}{copied ? "Copied" : "Copy SAP lines"}</Button></div><div className="space-y-2 p-4 font-mono text-[12px] leading-5 text-[#34503c]">{customer.sapLines.map((line, lineIndex) => <div key={`${line.fgCode}-${lineIndex}`} className="rounded-lg bg-[#f8faf6] px-3 py-2">{visibleSapLine(line)}</div>)}</div></CardContent></Card>;
}
