import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { buildRouteReportFromRows, filterRouteCustomers, formatUnits, type RouteReport } from "@/lib/routeReport";
import { Building2, FileSpreadsheet, Filter, Loader2, MapPinned, Paperclip, Route, ShieldCheck, Upload, UsersRound, X } from "lucide-react";
import React, { useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { toast } from "sonner";

function ProductRow({ code, name, quantity }: { code: string | null; name: string; quantity: number }) {
  return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-[#edf0e9] py-3 last:border-0"><div className="min-w-0"><p className="text-[13px] font-semibold leading-5 text-[#25372a]">{name}</p>{code && <p className="mt-0.5 font-mono text-[10px] tracking-[0.08em] text-[#7c897d]">{code}</p>}</div><div className="rounded-lg bg-[#eaf5df] px-2.5 py-1.5 text-right"><p className="text-base font-bold leading-none text-[#23583a]">{formatUnits(quantity)}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.12em] text-[#58775d]">Units</p></div></div>;
}

export default function RouteOrders() {
  const [report, setReport] = useState<RouteReport | null>(null);
  const [fileName, setFileName] = useState("");
  const [route, setRoute] = useState("all");
  const [category, setCategory] = useState("all");
  const [isReading, setIsReading] = useState(false);
  const [isDragActive, setIsDragActive] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const dragDepth = useRef(0);

  const receiveFile = async (file?: File) => {
    if (!file || isReading) return;
    const extension = file.name.split(".").pop()?.toLowerCase();
    if (!["xlsx", "xls"].includes(extension ?? "")) { toast.error("Please upload an Excel XLSX or XLS day-end sales report."); return; }
    if (file.size > 14_000_000) { toast.error("Please use an Excel file smaller than 14 MB."); return; }
    try {
      setIsReading(true);
      const workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellText: true, cellDates: true });
      const firstSheet = workbook.Sheets[workbook.SheetNames[0] ?? ""];
      if (!firstSheet) throw new Error("No readable worksheet was found in this file.");
      const rows = XLSX.utils.sheet_to_json<unknown[]>(firstSheet, { header: 1, defval: "", raw: false });
      const nextReport = buildRouteReportFromRows(rows);
      if (nextReport.customers.length === 0) throw new Error("No customer products with positive quantities were found in this sheet.");
      setReport(nextReport); setFileName(file.name); setRoute(nextReport.routes[0] ?? ""); setCategory("all");
      toast.success(`${nextReport.customers.length} customers across ${nextReport.routes.length} routes are ready. Select one route to share.`);
    } catch (error) { toast.error(error instanceof Error ? error.message : "This day-end report could not be read."); }
    finally { setIsReading(false); }
  };

  const customers = useMemo(() => report && route ? filterRouteCustomers(report, route, category) : [], [report, route, category]);
  const routeUnits = useMemo(() => customers.reduce((total, customer) => total + customer.totalUnits, 0), [customers]);
  const selectedLabel = [route, category !== "all" ? category.replace(/^CFS\s*-\s*/i, "") : "All categories"].filter(Boolean).join(" · ");
  const clearReport = () => { setReport(null); setFileName(""); setRoute("all"); setCategory("all"); if (inputRef.current) inputRef.current.value = ""; };

  return <div className="mx-auto max-w-[1480px] text-[#1d2b22]">
    <header className="mb-8 flex flex-col gap-5 border-b border-[#e5e4dc] pb-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#9ac55c]" /><span className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#607266]">Day-end sales review</span></div><h1 className="text-3xl font-semibold tracking-[-0.035em] sm:text-[38px]">Route-wise <span className="text-[#467752]">customer orders.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687067]">Select one route to open one complete, continuous customer-product board—ready for a single group-share screenshot.</p></div><div className="flex items-center gap-3 rounded-2xl border border-[#e3e3dc] bg-white px-4 py-3 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf4d9] text-[#467752]"><MapPinned className="h-4 w-4" /></div><div><p className="text-xs font-semibold">One route · one board</p><p className="mt-0.5 text-[11px] text-[#758077]">All customers together</p></div></div></header>

    <section onDragEnter={event => { event.preventDefault(); if (event.dataTransfer.files.length) { dragDepth.current += 1; setIsDragActive(true); } }} onDragOver={event => event.preventDefault()} onDragLeave={event => { event.preventDefault(); dragDepth.current -= 1; if (dragDepth.current <= 0) { dragDepth.current = 0; setIsDragActive(false); } }} onDrop={event => { event.preventDefault(); dragDepth.current = 0; setIsDragActive(false); void receiveFile(event.dataTransfer.files[0]); }} className={`rounded-[26px] border bg-white p-5 shadow-[0_14px_45px_-32px_rgba(26,49,32,0.3)] transition sm:p-7 ${isDragActive ? "border-[#6e9c5d] ring-4 ring-[#deedcf]" : "border-[#e4e4dd]"}`}>
      {!report ? <div className="flex min-h-52 flex-col items-center justify-center rounded-[20px] border-2 border-dashed border-[#d7e2d0] bg-[#fafcf8] px-6 py-8 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#eaf4df] text-[#356b42]"><FileSpreadsheet className="h-6 w-6" /></div><h2 className="mt-4 text-lg font-semibold">Upload day-end sales sheet</h2><p className="mt-1 max-w-md text-sm leading-6 text-[#718073]">Use the report that contains <b>Route</b>, <b>Cst Name</b>, <b>Cst Group</b>, and FG product columns. The file is read in your browser and is not saved.</p><input ref={inputRef} type="file" accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" className="hidden" onChange={event => void receiveFile(event.target.files?.[0])} /><Button type="button" onClick={() => inputRef.current?.click()} disabled={isReading} className="mt-5 h-10 rounded-xl bg-[#124e37] px-4 hover:bg-[#0e402e]">{isReading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}{isReading ? "Reading report…" : "Choose Excel file"}</Button><p className="mt-3 text-[11px] text-[#829083]">You can also drag and drop the file here.</p></div> : <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#eaf4df] text-[#356b42]"><FileSpreadsheet className="h-5 w-5" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{fileName}</p><p className="mt-0.5 text-xs text-[#6c7b6e]">{report.sourceRows} order rows · {report.customers.length} customers · {report.routes.length} routes</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => inputRef.current?.click()} className="h-9 rounded-lg border-[#cfddc9] bg-white text-xs text-[#325a3c] hover:bg-[#f3f8ee]"><Paperclip className="mr-1.5 h-3.5 w-3.5" />Change file</Button><Button variant="ghost" size="icon" onClick={clearReport} className="h-9 w-9 rounded-lg text-[#738075] hover:bg-[#f8f1ed] hover:text-[#9b482f]"><X className="h-4 w-4" /><span className="sr-only">Clear report</span></Button></div><input ref={inputRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={event => void receiveFile(event.target.files?.[0])} /></div>}
    </section>

    {report && <><section className="mt-5 rounded-[22px] border border-[#dfe7da] bg-[#f8faf5] p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[#46694c]"><Filter className="h-4 w-4" /><p className="text-xs font-bold uppercase tracking-[0.15em]">Route share filters</p></div><p className="mt-2 text-sm text-[#637364]">Select one route. All customers and their products for that route appear together in one board below.</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-[11px] font-bold uppercase tracking-[0.1em] text-[#617361]">Selected route<Select value={route} onValueChange={setRoute}><SelectTrigger className="h-10 min-w-[200px] border-[#d5e0d0] bg-white text-left font-medium normal-case tracking-normal text-[#263a2a]"><Route className="mr-2 h-4 w-4 text-[#52755a]" /><SelectValue placeholder="Select a route" /></SelectTrigger><SelectContent>{report.routes.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1.5 text-[11px] font-bold uppercase tracking-[0.1em] text-[#617361]">Customer category<Select value={category} onValueChange={setCategory}><SelectTrigger className="h-10 min-w-[200px] border-[#d5e0d0] bg-white text-left font-medium normal-case tracking-normal text-[#263a2a]"><Building2 className="mr-2 h-4 w-4 text-[#52755a]" /><SelectValue placeholder="All categories" /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{report.categories.map(item => <SelectItem key={item} value={item}>{item.replace(/^CFS\s*-\s*/i, "")}</SelectItem>)}</SelectContent></Select></label></div></div></section>
      <section aria-label="Single-route screenshot share board" className="mt-6 overflow-hidden rounded-[28px] border border-[#dce5d8] bg-white shadow-[0_16px_48px_-34px_rgba(26,49,32,0.32)]"><div className="bg-[#174c37] px-5 py-5 text-white sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/12"><MapPinned className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#bdd6c3]">One route · complete order board</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{selectedLabel}</h2></div></div><div className="flex flex-wrap gap-2"><span className="flex items-center gap-1.5 rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold text-[#ecf9e5]"><UsersRound className="h-4 w-4" />{customers.length} customer{customers.length === 1 ? "" : "s"}</span><span className="rounded-xl bg-[#dff0d4] px-3 py-2 text-xs font-bold text-[#24583a]">{formatUnits(routeUnits)} total units</span></div></div></div><div className="flex items-center justify-between border-b border-[#e5ebe1] bg-[#f6f9f3] px-5 py-3 sm:px-7"><p className="text-xs text-[#667766]">Every customer and every ordered product for the selected route is listed below.</p><div className="flex items-center gap-2 text-xs font-semibold text-[#3f6d45]"><ShieldCheck className="h-4 w-4" />Ready to screenshot & share</div></div>
        {customers.length === 0 ? <div className="flex min-h-64 flex-col items-center justify-center text-center"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#f6eee8] text-[#a75d3f]"><Filter className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">No customer orders match this route and category</h3><p className="mt-1 text-sm text-[#718073]">Choose another category or selected route.</p></div> : <div className="divide-y divide-[#e7ece4]">{customers.map((customer, index) => <Card key={customer.id} className="rounded-none border-0 bg-white shadow-none"><CardContent className="p-0"><div className="grid gap-4 p-5 sm:grid-cols-[260px_minmax(0,1fr)] sm:p-6"><div className="border-b border-[#e6ece2] pb-4 sm:border-b-0 sm:border-r sm:pb-0 sm:pr-5"><div className="flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#e7f2dd] text-[11px] font-bold text-[#2d603d]">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0"><p className="text-[17px] font-bold leading-6 text-[#213625]">{customer.customerName}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-md bg-[#f4f8f1] px-2 py-1 text-[10px] font-bold text-[#47644c]">{customer.category.replace(/^CFS\s*-\s*/i, "")}</span>{customer.customerCode && <span className="rounded-md bg-[#f4f8f1] px-2 py-1 font-mono text-[10px] text-[#647467]">{customer.customerCode}</span>}</div>{customer.salesOrders.length > 0 && <p className="mt-3 text-[11px] text-[#718173]">SO: {customer.salesOrders.join(", ")}</p>}</div></div><div className="mt-4 inline-flex rounded-xl bg-[#dff0d4] px-3 py-2 text-center sm:ml-11"><p className="text-base font-bold leading-none text-[#24583a]">{formatUnits(customer.totalUnits)}</p><p className="ml-2 text-[9px] font-bold uppercase tracking-[0.1em] text-[#5d785f]">Total units</p></div></div><div className="min-w-0">{customer.products.map(product => <ProductRow key={product.code ?? product.name} {...product} />)}</div></div></CardContent></Card>)}</div>}
      </section></>}
  </div>;
}
