import * as XLSX from "xlsx";
import type { ParsedOrderResult } from "../shared/orderTypes";

export type BranchStockInput = {
  branchName: string;
  parsed: ParsedOrderResult;
};

export type BranchStockSummary = {
  branchName: string;
  totalPkts: number;
  matchedProductCount: number;
  unmatchedFgCodes: string[];
  warnings: string[];
};

export type GeneratedStockSheet = {
  data: Buffer;
  summaries: BranchStockSummary[];
};

const TEMPLATE_SAP_ROW = 7;
const FIRST_BRANCH_ROW = 9;

function codeColumnMap(sheet: XLSX.WorkSheet): Map<string, number> {
  const range = XLSX.utils.decode_range(sheet["!ref"] || "A1:A1");
  const map = new Map<string, number>();
  for (let column = range.s.c; column <= range.e.c; column += 1) {
    const cell = sheet[XLSX.utils.encode_cell({ r: TEMPLATE_SAP_ROW - 1, c: column })];
    const code = typeof cell?.v === "string" ? cell.v.trim().toUpperCase() : "";
    if (/^(?:S?FG)-\d{2}-\d{4}$/i.test(code)) map.set(code, column);
  }
  return map;
}

function branchQuantities(parsed: ParsedOrderResult): Map<string, number> {
  const quantities = new Map<string, number>();
  parsed.customers.forEach(customer => customer.sapLines.forEach(line => quantities.set(line.fgCode, (quantities.get(line.fgCode) || 0) + line.qtyPkts)));
  return quantities;
}

function setText(sheet: XLSX.WorkSheet, address: string, value: string) {
  sheet[address] = { t: "s", v: value };
}

function setNumber(sheet: XLSX.WorkSheet, address: string, value: number) {
  sheet[address] = { t: "n", v: value };
}

export function populateStockSheet(template: Buffer, branches: BranchStockInput[]): GeneratedStockSheet {
  const workbook = XLSX.read(template, { type: "buffer", cellStyles: true, cellFormula: true });
  const sheet = workbook.Sheets.OrderSheet;
  if (!sheet) throw new Error("The stock-sheet template is missing the required OrderSheet worksheet.");
  const codeColumns = codeColumnMap(sheet);
  if (codeColumns.size === 0) throw new Error("No SAP code columns were found in the OrderSheet template.");
  const summaries = branches.map((branch, branchIndex) => {
    const row = FIRST_BRANCH_ROW + branchIndex;
    const quantities = branchQuantities(branch.parsed);
    const unmatchedFgCodes = Array.from(quantities.keys()).filter(fgCode => !codeColumns.has(fgCode));
    const warnings = [...branch.parsed.generalWarnings, ...branch.parsed.customers.flatMap(customer => customer.warnings)];
    setNumber(sheet, `A${row}`, branchIndex + 1);
    setText(sheet, `C${row}`, branch.branchName);
    setText(sheet, `E${row}`, "Branch order");
    setText(sheet, `F${row}`, "Generated by Cheese Desk");
    codeColumns.forEach((column, fgCode) => setNumber(sheet, XLSX.utils.encode_cell({ r: row - 1, c: column }), quantities.get(fgCode) || 0));
    return {
      branchName: branch.branchName,
      totalPkts: Array.from(quantities.values()).reduce((sum, value) => sum + value, 0),
      matchedProductCount: Array.from(quantities.keys()).filter(fgCode => codeColumns.has(fgCode)).length,
      unmatchedFgCodes,
      warnings: Array.from(new Set(warnings)).slice(0, 8),
    };
  });
  const data = XLSX.write(workbook, { type: "buffer", bookType: "xlsx", cellStyles: true });
  return { data, summaries };
}
